name = "backend"
main = "src/index.ts"

compatibility_date = "2022-11-22"

[vars]
COOKIE_SECRET = "XFS2DVYZskm4g9EXqRJFrwFcftqm0FWk9hicznhhhQ4"

[[d1_databases]]
binding = "DB"
database_name = "attend-stamp"
database_id = "f4993fbe-c093-4b99-b553-4ecdadf39775"
